-- Shared daily staff status: employees can mark one or more active coworkers as left today.

create table if not exists public.daily_staff_status (
  id bigint generated by default as identity primary key,
  work_date date not null default current_date,
  staff_id bigint not null references public.staff(id) on delete cascade,
  staff_name text not null,
  status text not null default 'left' check (status in ('left')),
  note text,
  reported_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (work_date, staff_id)
);

alter table public.daily_staff_status enable row level security;

create policy "employees read daily staff status" on public.daily_staff_status
  for select to authenticated
  using ((select public.is_admin()) or ((select public.is_cryo_employee()) and work_date = current_date));

create policy "employees create today's staff status" on public.daily_staff_status
  for insert to authenticated
  with check (
    (select public.is_cryo_employee())
    and work_date = current_date
    and reported_by = (select auth.uid())
    and exists (select 1 from public.staff s where s.id = daily_staff_status.staff_id and s.active)
  );

create policy "employees update today's staff status" on public.daily_staff_status
  for update to authenticated
  using ((select public.is_admin()) or ((select public.is_cryo_employee()) and work_date = current_date))
  with check (
    ((select public.is_admin()) or ((select public.is_cryo_employee()) and work_date = current_date))
    and reported_by = (select auth.uid())
    and exists (select 1 from public.staff s where s.id = daily_staff_status.staff_id and s.active)
  );

grant select, insert, update on public.daily_staff_status to authenticated;
grant usage, select on sequence public.daily_staff_status_id_seq to authenticated;

drop policy if exists "staff read access" on public.staff;
create policy "staff read access" on public.staff
  for select to authenticated
  using ((select public.is_admin()) or ((select public.is_cryo_employee()) and active));

drop policy if exists "admins update customers" on public.customers;
drop policy if exists "employees update customers" on public.customers;
create policy "employees update customers" on public.customers
  for update to authenticated
  using ((select public.is_cryo_employee()))
  with check ((select public.is_cryo_employee()));
grant update on public.customers to authenticated;
